version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    privileged: true
    restart: always
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - /usr/local/docker/postgres/data:/var/lib/postgresql/data
