version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    command:
      /bin/bash -c "redis-server /etc/redis/redis.conf"
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - /usr/local/docker/redis/data:/data
      - /usr/local/docker/redis/logs:/logs
